# We're not actually using C, but Travis doesn't have anything like TeX lang. :p
language: c

addons:
  apt:
    update: true
    packages:
      - aspell
      - aspell-en
      - latex-xcolor
      - texlive-latex-base

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      script:
        - aspell --lang=en create master ./words.dict < words
        - ./test.sh ./words.dict sections/*.tex

    - stage: build # and deploy
      script:
        - pdflatex -halt-on-error -interaction=nonstopmode resume.tex
      deploy:
        provider: releases
        # api_key:
        #   secure: roK7og03xDl7GjMhqWoOCb9gBdimZIdpd5PqHyQwQqhnvG4gROAX76La8JLdUvDNIeEhndQTlu3aUp5xflNFBC5mm6aV/CRwv8Q7Jw3zehYQNxF9cLTRfUcmrM3JwgbEqi8muHfQ069dNz9qISumQB/oMWhldtjRm/3IjUJuSrM=
        file: resume.pdf
        overwrite: true
        skip_cleanup: true
        on:
          branch: master
          tags: true
          repo: Anaka/resume
